# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d573e99c3e67149f0e0a63173e7bbbcd53bab89d9f0e7231b8f95691e150dd1ba2232c1da8f510e047619fd6d4027cf38b9103b7a6eecec679b0ffb13212955
  echonest_api_key: <%= ENV["ECHONEST_API_KEY"] %>

test:
  secret_key_base: a312bceb58f07e26eeec8535934b9e5e4a5293cf52cbbb1efb76da7ece9e81e0202f819b94919f41f024a1b0de88e3490c12fc40003cce0addd061ae8d7f843b
  echonest_api_key: <%= ENV["ECHONEST_API_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  echonest_api_key: <%= ENV["ECHONEST_API_KEY"] %>
